#!/usr/bin/env python3
"""Publish the un-cherry-picked qualitative examples both final reviews asked for.

Two blocks, one committed selection rule each:

  BLOCK 1 - every L0 `diff` claim, verbatim. Not a sample: the complete set, which is what
            Amendment 3 item 4 promised ("the verbatim claim text of ALL L0 verdicts,
            un-cherry-picked"). Each carries the direction-resolved reading from
            results/analysis/l0_direction_table.json so the reader sees which model the
            asymmetry was pinned on.

  BLOCK 2 - two planted-rung claims per rung (L1, L2, L3), drawn with
            `random.Random(SEED).sample(...)` over the runs sorted by (condition, run_id),
            with their human, judge and final grades and the graders' own reasons.

The seed is a CLI argument and is printed in the output, so the draw is reproducible and
was not re-rolled until it looked good. Claim text, quotes and grading reasons are copied
verbatim; nothing here is paraphrased or summarised.

No file under data/sealed/ is read.

    python scripts/random_examples.py
    python scripts/random_examples.py --seed 20260903 --out writeup/EXAMPLES_RANDOM.md
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

SEED = 20260903
RUNGS = ("L1", "L2", "L3")
PER_RUNG = 2


def read_jsonl(path: Path):
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if line:
            yield json.loads(line)


def condition_of(row: dict) -> str:
    """Same rule as scripts/analysis_join.py: the row's field wins, else the run_id prefix."""
    c = row.get("condition")
    if c:
        return c
    rid = row["run_id"]
    for prefix, cond in (("v0_cand_", "v0_opus"), ("v1_cand_", "v1_opus"),
                         ("bat_cand_", "battery"), ("intro_cand_", "introspection")):
        if rid.startswith(prefix):
            return cond
    return "unknown"


def final_grade(g: dict) -> str:
    return g.get("adjudicated_grade") or g.get("human_grade")


def quotes_of(claim: dict) -> list[str]:
    out = []
    for q in claim.get("supporting_quotes") or []:
        if isinstance(q, dict):
            t = q.get("quote")
            turn = q.get("turn")
            out.append(f"(turn {turn}) {t}" if turn else str(t))
        else:
            out.append(str(q))
    return [t for t in out if t and t != "None"]


def blockquote(text: str) -> str:
    text = (text or "").strip()
    if not text:
        return "> *(empty)*"
    return "\n".join("> " + ln if ln.strip() else ">" for ln in text.splitlines())


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--repo", default=str(Path(__file__).resolve().parents[1]))
    ap.add_argument("--seed", type=int, default=SEED)
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    repo = Path(a.repo).resolve()
    out = Path(a.out) if a.out else repo / "writeup" / "EXAMPLES_RANDOM.md"

    claims = {}
    for row in read_jsonl(repo / "results" / "phase1_claims.jsonl"):
        claims[(condition_of(row), row["run_id"])] = row
    grades = {}
    for row in read_jsonl(repo / "results" / "phase2_grades.jsonl"):
        grades[(condition_of(row), row["run_id"])] = row

    dtab_path = repo / "results" / "analysis" / "l0_direction_table.json"
    dtab = json.loads(dtab_path.read_text(encoding="utf-8")) if dtab_path.exists() else None
    directions = {}
    if dtab:
        for r in dtab["fp_rows"]:
            directions[(r["condition"], r["run_id"])] = r

    # ---- block 1: every L0 `diff` claim, complete set
    l0_diff = sorted(k for k, g in grades.items()
                     if g.get("rung") == "L0"
                     and (claims.get(k) or {}).get("verdict_type") == "diff")
    l0_fp = sorted(k for k, g in grades.items()
                   if g.get("rung") == "L0" and final_grade(g) == "FP")
    consistency = ("the two sets are identical, as the frozen rule requires"
                   if l0_diff == l0_fp else
                   f"MISMATCH - diff claims {l0_diff} vs FP grades {l0_fp}")

    # ---- block 2: seeded draw per rung
    rng = random.Random(a.seed)
    picks = {}
    pools = {}
    for rung in RUNGS:
        pool = sorted(k for k, g in grades.items()
                      if g.get("rung") == rung and k in claims
                      and g.get("human_grade") != "REFUSAL_NO_VERDICT")
        pools[rung] = pool
        picks[rung] = sorted(rng.sample(pool, min(PER_RUNG, len(pool))))

    L, A = [], None
    A = L.append
    A("# Random and complete raw examples — verbatim claim text with grades")
    A("")
    A("Generated by `scripts/random_examples.py`. Claim text, supporting quotes and grading "
      "reasons are **copied verbatim** from `results/phase1_claims.jsonl` and "
      "`results/phase2_grades.jsonl`; nothing on this page is paraphrased. No file under "
      "`data/sealed/` is read.")
    A("")
    A(f"- **Selection rule, block 1:** every L0 claim whose Phase-1 `verdict_type` is `diff` "
      f"— the complete set, not a sample (Amendment 3 item 4). **n = {len(l0_diff)}.** "
      f"Cross-check against the L0 rows graded FP: {consistency}.")
    A(f"- **Selection rule, block 2:** `random.Random({a.seed}).sample(pool, {PER_RUNG})` per "
      f"rung, where `pool` is every graded, verdict-bearing run of any condition on that rung "
      f"sorted by `(condition, run_id)`. Pool sizes: "
      f"{', '.join(f'{r} {len(pools[r])}' for r in RUNGS)}. The seed is a committed CLI "
      f"default; re-running reproduces this exact draw.")
    A("")
    A("---")
    A("")
    A(f"## Block 1 — all {len(l0_diff)} L0 `diff` claims (the null-trained control)")
    A("")
    A("Every one of these is a **false positive under the frozen rule** "
      "(`PREREGISTRATION.md` Addendum A §1) and stays one. The *direction* line under each is "
      "the post-hoc, mechanical reading from `results/analysis/l0_direction_table.md` — which "
      "model the agent pinned the asymmetry on, once `run_meta.label_map` is applied.")
    A("")
    for k in l0_diff:
        cond, rid = k
        c, g = claims[k], grades[k]
        d = directions.get(k)
        A(f"### `{cond}` / `{rid}` — final grade **{final_grade(g)}**, agent confidence "
          f"{c.get('agent_stated_confidence')}")
        A("")
        if d:
            A(f"- label_map: `{json.dumps(d['label_map'])}` → the candidate "
              f"(`{d['candidate_id']}`) served as **{d['candidate_letter'] or 'n/a'}**")
            for name, res in sorted((d.get("families") or {}).items()):
                A(f"- direction ({name}): **{res['direction']}**")
            if d.get("replicated_by"):
                for name, others in d["replicated_by"].items():
                    A(f"- replicates ({name}): {', '.join(others)}")
        A("")
        A("**Hypothesis, verbatim:**")
        A("")
        A(blockquote(c.get("top_hypothesis_verbatim")))
        A("")
        qs = quotes_of(c)
        if qs:
            A("**Supporting quotes, verbatim:**")
            A("")
            for q in qs:
                A(blockquote(q))
                A("")
        dis = c.get("explicit_disconfirming_evidence")
        if dis and str(dis).strip() and str(dis) != "None":
            A("**Disconfirming evidence the agent recorded itself, verbatim:**")
            A("")
            A(blockquote(str(dis)))
            A("")
        A(f"**Grades** — human `{g.get('human_grade')}` · judge `{g.get('judge_grade')}` · "
          f"adjudicated `{g.get('adjudicated_grade')}` · final **{final_grade(g)}**")
        A("")
        if g.get("human_reason"):
            A("Human reason, verbatim:")
            A("")
            A(blockquote(g["human_reason"]))
            A("")
        if g.get("adjudication_reason"):
            A("Adjudication reason, verbatim:")
            A("")
            A(blockquote(g["adjudication_reason"]))
            A("")
        A("---")
        A("")

    A("## Block 2 — two planted-rung claims per rung, drawn by seed")
    A("")
    for rung in RUNGS:
        A(f"### {rung}")
        A("")
        for k in picks[rung]:
            cond, rid = k
            c, g = claims[k], grades[k]
            A(f"#### `{cond}` / `{rid}` — final grade **{final_grade(g)}**, agent confidence "
              f"{c.get('agent_stated_confidence')}, Phase-1 verdict type "
              f"`{c.get('verdict_type')}`")
            A("")
            A("**Hypothesis, verbatim:**")
            A("")
            A(blockquote(c.get("top_hypothesis_verbatim")))
            A("")
            qs = quotes_of(c)
            if qs:
                A("**Supporting quotes, verbatim:**")
                A("")
                for q in qs:
                    A(blockquote(q))
                    A("")
            A(f"**Grades** — human `{g.get('human_grade')}` · judge `{g.get('judge_grade')}` "
              f"· adjudicated `{g.get('adjudicated_grade')}` · final **{final_grade(g)}**")
            A("")
            if g.get("human_reason"):
                A("Human reason, verbatim:")
                A("")
                A(blockquote(g["human_reason"]))
                A("")
            if g.get("judge_reason"):
                A("Judge reason, verbatim:")
                A("")
                A(blockquote(g["judge_reason"]))
                A("")
            if g.get("adjudication_reason"):
                A("Adjudication reason, verbatim:")
                A("")
                A(blockquote(g["adjudication_reason"]))
                A("")
            dec = g.get("decomposition") or {}
            if dec:
                A(f"Addendum D as entered on the card: `{json.dumps(dec)}` — for L1–L3 the "
                  f"script-derived values are in "
                  f"`results/analysis/decomposition_transcripts.md`.")
                A("")
            A("---")
            A("")

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {out}")
    print(f"block 1: {len(l0_diff)} L0 diff claims ({consistency})")
    for rung in RUNGS:
        print(f"block 2 {rung}: {[f'{c}:{r}' for c, r in picks[rung]]} "
              f"(pool {len(pools[rung])})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
